---
version: 0.2
phases:
  install:
    commands:
    - pip install -r requirements.txt -t ./
  post_build:
    commands:
      - aws cloudformation package --template template.yaml --s3-bucket arn:aws:s3:::mirabot-development
artifacts:
  type:
    files:
    - gitHandler.py
    - template.json
